package com.br.second.tech.challenge.core.exception;

public class UsuarioNotFoundException extends RuntimeException {

    public UsuarioNotFoundException(String msg) {
        super(msg);
    }
}
